- name: installation file
  hosts: all
  become: true
  tasks:
    - name: install apache2
      apt:
          name: apache2
          state: latest
          update-cache: yes
    
    - name: Check Apache status
      command: service apache2 status
      register: apache_status

    - name: Display Apache status
      debug:
        msg: "Apache2 service status: {{ apache_status.stdout }}"

    - name: package module
      package:
        name: nginx
        state: present
      when: ansible_os_family=="Debian"
  
  #start apache2 service
    - name: start the service
      systemd: 
        name: apache2
        state: started
        enabled: yes

#copy index document
    - name: copy index file in apache2 server
      copy:
        src: ./index.html
        dest: /var/www/html/index.html
