- name: installation file
  hosts: all
  become: true
  tasks:
    - name: install apache2
      apt:
          name: apache2
          state: latest
          update-cache: yes
    
    - name: Check Apache status
      command: service apache2 status
      register: apache_status

    - name: Display Apache status
      debug:
        msg: "Apache2 service status: {{ apache_status.stdout }}"

    - name: package module
      package:
        name: nginx
        state: present
      when: ansible_os_family=="Debian"
