- name: loop file
  hosts: all
  become: true
  tasks:
    - name: looping statement
      debug:
        msg: "{{item}}"
      loop:
        - apple
        - mango
        - orange

  # add packages through loop
    - name: add packages
      package: 
        name: "{{item}}"
        state: latest
      loop:
        - vim
        - nginx
        - wget