- name: print msg
  debug: 
    msg: "this is first role"

- name: print varible
  debug:
    msg: "this is varible name {{text}}"

- name: install httpd
  package:
    name: httpd
    state: latest
      

- name: copy index.html file
  copy:
    src: index.html
    dest: /var/www/html/index.html